hpc<-read.table(file="household_power_consumption.txt",na.strings = "?", sep = ";", header = T)
hpc_subset<-subset(hpc,Date=="1/2/2007"|Date=="2/2/2007")
#add a column with date and time
hpc_subset<-cbind(hpc_subset,dateTime=as.POSIXct(paste(hpc_subset$Date, hpc_subset$Time), format="%d/%m/%Y %H:%M:%S"))
png(filename = "plot4.png")
par(mfrow=c(2,2))
plot(hpc_subset$Global_active_power~hpc_subset$dateTime,type="l",xlab = NA, ylab = "Global Active Power")
plot(hpc_subset$Voltage~hpc_subset$dateTime,type="l",xlab = "datetime", ylab = "Voltage")
plot(x = hpc_subset$dateTime,y = hpc_subset$Sub_metering_1,xlab = NA, ylab = "Energy sub metering", type="l")
lines(x=hpc_subset$dateTime,y=hpc_subset$Sub_metering_2, col="red", type = "l")
lines(x=hpc_subset$dateTime,y=hpc_subset$Sub_metering_3, col="blue", type = "l")
legend(x = "topright", legend =  c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = 1, bty = "n")
with(hpc_subset,plot(Global_reactive_power~dateTime,type="l",xlab = "datetime"))
dev.off()